CREATE TABLE IF NOT EXISTS votes (
  ID INTEGER NOT NULL,
  YEAR INTEGER NOT NULL,
  CAR_CLASS_RID INTEGER NOT NULL REFERENCES car_classes (ID),
  CAR_NUMBER INTEGER NOT NULL
  CONSTRAINT votes_pk PRIMARY KEY (ID)
);

CREATE SEQUENCE IF NOT EXISTS vote_id_sequence START WITH 1;

DROP TRIGGER IF EXISTS bir_votes ON votes;
DROP FUNCTION IF EXISTS bir_votes();

CREATE FUNCTION bir_votes() RETURNS trigger as $bir_votes$
BEGIN
  IF NEW.id IS NULL THEN
    NEW.id := nextval('vote_id_sequence');
  END IF;
  RETURN NEW;
END;
$bir_votes$ LANGUAGE plpgsql;

CREATE TRIGGER bir_votes BEFORE INSERT ON votes
    FOR EACH ROW EXECUTE PROCEDURE bir_votes();

